elk:
  url: "http://elastic:admin123@localhost:9200/"
  index_destination:
    employee: "dev-master-pegawai-dukcapil"
    web_portal: "dev-query-dukcapil"
    quota_dukcapil: "dev-master-quota-dukcapil"

db:
  url: sqlite:///csv_elastic.sqlite
